/// Flutter icons CardIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CardIcons
///      fonts:
///       - asset: fonts/CardIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class CardIcons {
  CardIcons._();

  static const _kFontFam = 'CardIcons';
  static const String? _kFontPkg = null;

  static const IconData wondrousItem = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weapon = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData staff = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wand = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ring = IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armour = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData potion = IconData(0xea72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll = IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
